#%RAML 0.8

title: Word Cloud Generator API
baseUri: http://localhost:8888

/api:
  post:
    body:
      application/json:
        schema: |
          text: 'string'
        example: |
              { "text": "What does the fox say? Ring a ding ding ding ding a ding a ding" }
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema"
              }
            example: |
              {
                  "a": 3,
                  "ding": 6,
                  "does": 1,
                  "fox": 1,
                  "ring": 1,
                  "say?": 1,
                  "the": 1,
                  "what": 1
              }
/version:
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "version": "string"
              }
            example: |
              { "version": "1.43" }
          text/plain: